services:

  db_service:
    container_name: 'db_bot'
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - myNetwork
    volumes:
      - pg-panel-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"

  tg_bot_service:
    container_name: 'tg_bot'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - myNetwork
    env_file:
      - .env

networks:
  myNetwork:
    external: true

volumes:
  pg-panel-data: